name: MCCodeCamp
version: '${version}'

main: me.simoncrafter.mCCodeCamp.MCCodeCamp
api-version: '1.21.1'

commands:
  createInput:
    description: "Creates an input that can be used in code"
  reloadMCCodeCampInterface: {}